language: go
sudo: required
addons:
  apt:
    packages:
    - lynx
    - jq
    - wget
    - grep
go: 1.10
before_script:
- sudo rsync -az ${TRAVIS_BUILD_DIR}/ /usr/local/bootstrap/
- bash scripts/generate_certificates.sh
- bash scripts/install_consul.sh
- bash scripts/consul_enable_acls.sh
script:
- source ./var.env
- export LEADER_IP=127.0.0.1
- bash scripts/initialise_terraform_consul_backend.sh

